import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
from dataclasses import dataclass

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

@dataclass(slots=True)
class MfStruct:
    cust: str
    count_1_quant: int

mf_struct = []

def lookup(cur_row):
    '''Search for all indices in the mf_struct that match the current group'''
    for i in range(len(mf_struct)):
        if mf_struct[i].cust == cur_row['cust']:
            return i
    return -1

def add(cur_row):
    '''Adds a new entry in mf_struct corresponding to a newly found group by attribute value'''
    mf_struct.append(MfStruct(cust=cur_row['cust'], count_1_quant=0))

def output():
    '''Returns only the select attributes of mf_struct'''
    mf_struct_table = [{
        'cust': entry.cust,
        'count_1_quant': entry.count_1_quant
    } for entry in mf_struct]
    return mf_struct_table

def print_output(table):
    '''Prints final table to stdout'''
    print(tabulate.tabulate(table, headers="keys", tablefmt="psql"))

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    table = cur.fetchall()

    # Table scan 0: Populate mf_struct with distinct values of grouping attributes
    for row in table:
        pos = lookup(row)
        if pos == -1:
            add(row)

    # Table scan for grouping variable 1
    for cur_row in table:
        for i in range(len(mf_struct)):
            if cur_row['state'] == 'NY':
                mf_struct[i].count_1_quant += 1

    return output()

def main():
    table = query()
    print_output(table)
    
if "__main__" == __name__:
    main()