import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
from dataclasses import dataclass

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

@dataclass(slots=True)
class MfStruct:
	cust: str
	sum_1_quant: int
	avg_1_quant: int
	sum_2_quant: int
	sum_3_quant: int
	avg_3_quant: int

mf_struct = []


def lookup(cur_row):
    '''Search for a given "group by" attribute value(s) in mf_struct'''
    for i in range(len(mf_struct)):
        if mf_struct[i].cust == cur_row.cust:
            return i
    return -1

def add(cur_row):
    '''Adds a new entry in mf_struct corresponding to a newly found group by attribute value'''
    mf_struct.append(MfStruct(cust=cur_row.cust, sum_1_quant=0, avg_1_quant=0, sum_2_quant=0, sum_3_quant=0, avg_3_quant=0))

def output():
    '''Prints mf_struct to stdout'''
    print("cust   sum_1_quant   avg_1_quant   sum_2_quant   sum_3_quant   avg_3_quant")
    for entry in mf_struct:
        print(f"{entry.cust}   {entry.sum_1_quant}   {entry.avg_1_quant}   {entry.sum_2_quant}   {entry.sum_3_quant}   {entry.avg_3_quant}")


def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    for row in cur:
        if row['quant'] > 10:
            _global.append(row)
    
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    