"""
Team members: Nicolas Banatt CWID(20014265), Aidan Cancelliere CWID()

Generates a _generated.py file that outputs the result of a user's EMF query,
either from a file or from manual keyboard input.
"""

import subprocess
import sys

from input_handler import InputHandler
from phi import Phi

sales_schema = {
    "cust": "str",
    "prod": "str",
    "day": "int",
    "month": "int",
    "year": "int",
    "state": "str",
    "quant": "int",
    "date": "str"
}

# def generate_code_from_pred(pred: str) -> str:
#     """
#     Generates python code snippet from a grouping variable predicate input by the user.

#     Ex. input: "1.product=product and 1.quant > avg_quant" -> 
#         output: "row['product'] == mf_struct[pos].product and row['quant'] > mf_struct[pos].avg_quant"
#     """

def main():
    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """

    phi: Phi = InputHandler().get_phi_expr()
    print(phi)

    # Constructing the mf_struct fields (V + F)
    struct_fields = ""
    for attr in phi.V:
        struct_fields += f"\t{attr}: {sales_schema[attr]}\n"
    for agg in phi.F:
        struct_fields += f"\t{agg}: int\n"

    # Code to define the mf_struct
    mf_struct = f"""
@dataclass(slots=True)
class MfStruct:
{struct_fields}
mf_struct = []
"""
    
    # Database helper functions
    helpers = f"""
def lookup(cur_row):
    '''Search for a given "group by" attribute value(s) in mf_struct'''
    for i in range(len(mf_struct)):
        if {" and ".join([f"mf_struct[i].{attr} == cur_row['{attr}']" for attr in phi.V])}:
            return i
    return -1

def add(cur_row):
    '''Adds a new entry in mf_struct corresponding to a newly found group by attribute value'''
    mf_struct.append(MfStruct({", ".join(
        [f"{attr}=cur_row['{attr}']" for attr in phi.V] +
        [f"{aggr}={-1 if 'max' in aggr else 0}" for aggr in phi.F]
    )}))

def output():
    '''Prints only the select attributes of mf_struct to stdout'''
    # print("{'   '.join([field for field in phi.S])}")
    # for entry in mf_struct:
    #     print(f"{'   '.join([f'{{entry.{field}}}' for field in phi.S])}")

    mf_struct_table = [({', '.join([f"entry.{attr}" for attr in phi.S])}) for entry in mf_struct]
    print(tabulate.tabulate(mf_struct_table, headers={phi.S}, tablefmt="psql"))
"""
    
    # Code for first table scan to populate mf_struct
    populate_mf_struct = """
    # Table scan 1: Populate mf_struct with distinct values of grouping attributes
    for row in table:
        pos = lookup(row)
        if pos == -1:
            add(row)
    """

    # compute_aggregates = [f"""
    # for row in table:
    #     pos = lookup(row)
    #     if {generate_code_from_pred(phi.o[i])}:
    # """ for i in range(phi.n)]

    body = f"""
    for row in cur:
        table.append(row)
    {populate_mf_struct}
    """

    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
from dataclasses import dataclass

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py
{mf_struct}
{helpers}

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    table = []
    {body}
    
    return tabulate.tabulate(table,
                        headers="keys", tablefmt="psql")

def main():
    #print(query())
    query()
    output()
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code using the same python.exe running this script
    subprocess.run([sys.executable, "_generated.py"])


if "__main__" == __name__:
    main()
