"""
Name: Nicolas Banatt
CWID: 20014265
"""

import subprocess
import sys

from input_handler import InputHandler
from phi import Phi

sales_schema = {
    "cust": "str",
    "prod": "str",
    "day": "int",
    "month": "int",
    "year": "int",
    "state": "str",
    "quant": "int",
    "date": "str"
}

def main():
    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """

    phi: Phi = InputHandler().get_phi_expr()
    print(phi)

    # Constructing the mf_struct fields (V + F)
    struct_fields = ""
    for attr in phi.V:
        struct_fields += f"\t{attr}: {sales_schema[attr]}\n"
    for agg in phi.F:
        struct_fields += f"\t{agg}: int\n"

    # Code to define the mf_struct
    mf_struct = f"""
@dataclass(slots=True)
class MfStruct:
{struct_fields}
mf_struct = []
"""
    
    # Database helper functions
    helpers = f"""
def lookup(cur_row):
    '''Search for a given "group by" attribute value(s) in mf_struct'''
    for i in range(len(mf_struct)):
        if {" and ".join([f"mf_struct[i].{attr} == cur_row.{attr}" for attr in phi.V])}:
            return i
    return -1

def add(cur_row):
    '''Adds a new entry in mf_struct corresponding to a newly found group by attribute value'''
    mf_struct.append(MfStruct({", ".join(
        [f"{attr}=cur_row.{attr}" for attr in phi.V] +
        [f"{aggr}={-1 if 'max' in aggr else 0}" for aggr in phi.F]
    )}))

def output():
    '''Prints mf_struct to stdout'''
    print("{'   '.join([field for field in phi.V + phi.F])}")
    for entry in mf_struct:
        print(f"{'   '.join([f'{{entry.{field}}}' for field in phi.V + phi.F])}")
"""

    body = """
    for row in cur:
        if row['quant'] > 10:
            _global.append(row)
    """

    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
from dataclasses import dataclass

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py
{mf_struct}
{helpers}

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code using the same python.exe running this script
    subprocess.run([sys.executable, "_generated.py"])


if "__main__" == __name__:
    main()
