"""
Team members: Nicolas Banatt CWID(20014265), Aidan Cancelliere CWID()

Generates a _generated.py file that outputs the result of a user's EMF query,
either from a file or from manual keyboard input.
"""

import subprocess
import sys

from input_handler import InputHandler
from phi import Phi

DEBUG = True

sales_schema = {
    "cust": "str",
    "prod": "str",
    "day": "int",
    "month": "int",
    "year": "int",
    "state": "str",
    "quant": "int",
    "date": "str"
}

def mf_struct(i: str, attr: str):
    """
    Generates python code to access the attribute at the ith element of the mf_struct.
    """
    return f"mf_struct[{i}].{attr}"

def row_proj(row_name: str, attr: str):
    """
    Generates python code to access an attribute of a tuple / row.
    """
    return f"{row_name}['{attr}']"

def generate_code_from_pred_operand(i: int, op: str) -> str:
    """
    Generates python code snippet from a single predicate operand.

    Ex. "1.state" -> "row['state']"
        "avg_2_quant -> 
    """
    pass

def generate_code_from_pred(i: int, phi: Phi) -> str:
    """
    Generates python code snippet from a grouping variable predicate input by the user.

    Ex. input: "1.product=product and 1.quant > avg_quant" -> 
        output: "row['product'] == mf_struct[pos].product and row['quant'] > mf_struct[pos].avg_quant"
    """
    pass

def generate_mf_struct_def(phi: Phi) -> str:
    """
    Generates python code to define the mf_struct.
    """
    # Constructing the mf_struct fields (V + F)
    struct_fields = ""
    for attr in phi.V:
        struct_fields += f"\t{attr}: {sales_schema[attr]}\n"
    for agg in phi.F:
        struct_fields += f"\t{agg}: int\n"

    # Code to define the mf_struct
    return f"""
@dataclass(slots=True)
class MfStruct:
{struct_fields}
mf_struct = []
    """


def generate_helpers(phi: Phi) -> str:
    """
    Generates python helper functions for the generated program.
    """
    return f"""
def lookup(cur_row):
    '''Search for all indices in the mf_struct that match the current group'''
    # indices = []
    pos = -1
    for i in range(len(mf_struct)):
        if {" and ".join([f"{mf_struct('i', attr)} == {row_proj('cur_row', attr)}" for attr in phi.V])}:
            return i
        # if
        #     indices.append(i)
    # return indices
    return pos

def add(cur_row):
    '''Adds a new entry in mf_struct corresponding to a newly found group by attribute value'''
    mf_struct.append(MfStruct({", ".join(
        [f"{attr}={row_proj('cur_row', attr)}" for attr in phi.V] +
        [f"{aggr}={-1 if 'max' in aggr else 0}" for aggr in phi.F]
    )}))

def output():
    '''Prints only the select attributes of mf_struct to stdout'''
    mf_struct_table = [({', '.join([f"entry.{attr}" for attr in phi.S])}) for entry in mf_struct]
    print(tabulate.tabulate(mf_struct_table, headers={phi.S}, tablefmt="psql"))
    """

def generate_body(phi: Phi) -> str:
    """
    Generates program logic within the main function.
    """
    # Code for first table scan to populate mf_struct
    populate_mf_struct = """
    # Table scan 1: Populate mf_struct with distinct values of grouping attributes
    for row in table:
        pos = lookup(row)
        #if not pos:
        if pos == -1:
            add(row)
    """

    return f"""
    for row in cur:
        table.append(row)
    {populate_mf_struct}
    """

def main():
    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """

    phi: Phi = InputHandler().get_phi_expr()
    if DEBUG: print(phi)
    
    mf_struct = generate_mf_struct_def(phi)   # mf_struct definition
    helpers = generate_helpers(phi)           # Database helper functions
    body = generate_body(phi)                 # Program logic
    
    # # Code for first table scan to populate mf_struct
    # populate_mf_struct = """
    # # Table scan 1: Populate mf_struct with distinct values of grouping attributes
    # for row in table:
    #     pos = lookup(row)
    #     if not pos:
    #         add(row)
    # """

    # emf_algorithm = ''.join([f"""
    # # Table scan {i+1} for grouping variable {i}
    # for row in table:
    #     for entry in mf_struct:
    #         if {generate_code_from_pred(i, phi)}:
    #             {generate_code_update_aggrs(i, phi)}
                
    # """ for i in range(phi.n + 1)])

    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
from dataclasses import dataclass

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py
{mf_struct}
{helpers}

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    table = []
    {body}
    
    return tabulate.tabulate(table,
                        headers="keys", tablefmt="psql")

def main():
    #print(query())
    query()
    output()
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code using the same python.exe running this script
    subprocess.run([sys.executable, "_generated.py"])


if "__main__" == __name__:
    main()
