import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
from dataclasses import dataclass

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

@dataclass(slots=True)
class MfStruct:
    cust: str
    prod: str
    avg_quant: int
    sum_quant: int
    count_quant: int
    max_quant: int

mf_struct = []

def lookup(cur_row):
    '''Search for all indices in the mf_struct that match the current group'''
    for i in range(len(mf_struct)):
        if mf_struct[i].cust == cur_row['cust'] and mf_struct[i].prod == cur_row['prod']:
            return i
    return -1

def add(cur_row):
    '''Adds a new entry in mf_struct corresponding to a newly found group by attribute value'''
    mf_struct.append(MfStruct(cust=cur_row['cust'], prod=cur_row['prod'], avg_quant=0, sum_quant=0, count_quant=0, max_quant=-1))

def output():
    '''Returns only the select attributes of mf_struct'''
    mf_struct_table = [{
        'cust': entry.cust,
        'prod': entry.prod,
        'avg_quant': entry.avg_quant,
        'max_quant': entry.max_quant
    } for entry in mf_struct]
    return mf_struct_table

def print_output(table):
    '''Prints final table to stdout'''
    print(tabulate.tabulate(table, headers="keys", tablefmt="psql"))

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    table = cur.fetchall()

    # Table scan 0: Populate mf_struct with distinct values of grouping attributes
    for row in table:
        pos = lookup(row)
        if pos == -1:
            add(row)

    # Table scan for grouping variable 0
    for cur_row in table:
        for i in range(len(mf_struct)):
            if cur_row['cust'] == mf_struct[i].cust and cur_row['prod'] == mf_struct[i].prod:
                mf_struct[i].sum_quant += cur_row['quant']
                mf_struct[i].count_quant += 1
                if mf_struct[i].max_quant < cur_row['quant']: mf_struct[i].max_quant = cur_row['quant']
    # Compute averages for grouping variable 0 at end of scan
    for i in range(len(mf_struct)):
        mf_struct[i].avg_quant = mf_struct[i].sum_quant / mf_struct[i].count_quant

    return output()

def main():
    table = query()
    print_output(table)
    
if "__main__" == __name__:
    main()