import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
from dataclasses import dataclass

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

@dataclass(slots=True)
class MfStruct:
    cust: str
    avg_quant: int
    sum_quant: int
    count_quant: int
    avg_1_quant: int
    sum_1_quant: int
    count_1_quant: int
    sum_2_quant: int
    sum_3_quant: int
    max_3_quant: int

mf_struct = []

def lookup(cur_row):
    '''Search for all indices in the mf_struct that match the current group'''
    for i in range(len(mf_struct)):
        if mf_struct[i].cust == cur_row['cust']:
            return i
    return -1

def add(cur_row):
    '''Adds a new entry in mf_struct corresponding to a newly found group by attribute value'''
    mf_struct.append(MfStruct(cust=cur_row['cust'], avg_quant=0, sum_quant=0, count_quant=0, avg_1_quant=0, sum_1_quant=0, count_1_quant=0, sum_2_quant=0, sum_3_quant=0, max_3_quant=-1))

def output():
    '''Returns only the select attributes of mf_struct'''
    mf_struct_table = [{
        'cust': entry.cust,
        'avg_quant': entry.avg_quant,
        'avg_1_quant': entry.avg_1_quant,
        'sum_1_quant': entry.sum_1_quant,
        'sum_2_quant': entry.sum_2_quant,
        'sum_3_quant': entry.sum_3_quant,
        'max_3_quant': entry.max_3_quant
    } for entry in mf_struct]
    return mf_struct_table

def print_output(table):
    '''Prints final table to stdout'''
    print(tabulate.tabulate(table, headers="keys", tablefmt="psql"))

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    table = cur.fetchall()

    # Table scan 0: Populate mf_struct with distinct values of grouping attributes
    for row in table:
        pos = lookup(row)
        if pos == -1:
            add(row)

    # Table scan for grouping variable 0
    for cur_row in table:
        for i in range(len(mf_struct)):
            if cur_row['cust'] == mf_struct[i].cust:
                mf_struct[i].sum_quant += cur_row['quant']
                mf_struct[i].count_quant += 1
    # Compute averages for grouping variable 0 at end of scan
    for i in range(len(mf_struct)):
        mf_struct[i].avg_quant = mf_struct[i].sum_quant / mf_struct[i].count_quant


    # Table scan for grouping variable 1
    for cur_row in table:
        for i in range(len(mf_struct)):
            if cur_row['state'] == 'NY' and cur_row['cust'] == 'Mia':
                mf_struct[i].sum_1_quant += cur_row['quant']
                mf_struct[i].count_1_quant += 1
    # Compute averages for grouping variable 1 at end of scan
    for i in range(len(mf_struct)):
        mf_struct[i].avg_1_quant = mf_struct[i].sum_1_quant / mf_struct[i].count_1_quant


    # Table scan for grouping variable 2
    for cur_row in table:
        for i in range(len(mf_struct)):
            if cur_row['state'] == 'NJ':
                mf_struct[i].sum_2_quant += cur_row['quant']


    # Table scan for grouping variable 3
    for cur_row in table:
        for i in range(len(mf_struct)):
            if cur_row['state'] == 'CT':
                mf_struct[i].sum_3_quant += cur_row['quant']
                if mf_struct[i].max_3_quant < cur_row['quant']: mf_struct[i].max_3_quant = cur_row['quant']

    return output()

def main():
    table = query()
    print_output(table)
    
if "__main__" == __name__:
    main()